### ISSUE TITLE
gitlab token komprimitiert

### ISSUE THREAD

**Issue by kvlahromei** [tagliateller/ansible-d115#1]
Der geheime Zugangs-token wurde leider mit auf github gestellt [secrets.yml~](secrets.yml~). Am besten entfernen und für ungültig erklären.

**Comment by tagliateller** [comment]
Danke!

On 11. März 2016 08:57:31 MEZ, "Matthias Meißer" <notifications@github.com> wrote:
>Der geheime Zugangs-token wurde leider mit auf github gestellt
>[secrets.yml~](secrets.yml~). Am besten entfernen und für ungültig
>erklären.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/tagliateller/ansible-d115/issues/1

-- 
Diese Nachricht wurde von meinem Mobiltelefon mit Kaiten Mail gesendet.
